CREATE TABLE `appointments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`doctorId` int,
	`title` varchar(200) NOT NULL,
	`type` enum('consultation','followup','procedure','monitoring','lab_test','video_call') NOT NULL DEFAULT 'consultation',
	`date` timestamp NOT NULL,
	`duration` int DEFAULT 30,
	`status` enum('scheduled','confirmed','in_progress','completed','cancelled','no_show') NOT NULL DEFAULT 'scheduled',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `appointments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `billing_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`transactionId` varchar(30) NOT NULL,
	`service` varchar(300) NOT NULL,
	`category` enum('consultation','procedure','medication','lab_test','package','qna','other') NOT NULL DEFAULT 'other',
	`amount` decimal(10,2) NOT NULL,
	`discount` decimal(10,2) DEFAULT '0',
	`tax` decimal(10,2) DEFAULT '0',
	`totalAmount` decimal(10,2) NOT NULL,
	`paymentMethod` enum('cash','card','upi','net_banking','wallet','insurance'),
	`status` enum('pending','paid','overdue','refunded','cancelled') NOT NULL DEFAULT 'pending',
	`invoiceNumber` varchar(30),
	`paidAt` timestamp,
	`dueDate` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `billing_transactions_id` PRIMARY KEY(`id`),
	CONSTRAINT `billing_transactions_transactionId_unique` UNIQUE(`transactionId`)
);
--> statement-breakpoint
CREATE TABLE `clinical_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`doctorId` int,
	`assessmentType` enum('initial','hormonal','ultrasound','semen_analysis','hysteroscopy','laparoscopy','genetic') NOT NULL,
	`assessmentDate` timestamp NOT NULL,
	`findings` text,
	`diagnosis` text,
	`recommendations` text,
	`amh` decimal(5,2),
	`fsh` decimal(5,2),
	`lh` decimal(5,2),
	`estradiol` decimal(7,2),
	`progesterone` decimal(5,2),
	`tsh` decimal(5,2),
	`prolactin` decimal(6,2),
	`antralFollicleCount` int,
	`endometrialThickness` decimal(4,1),
	`status` enum('pending','completed','reviewed') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clinical_assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cycle_monitorings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cycleId` int NOT NULL,
	`patientId` int NOT NULL,
	`monitoringDate` timestamp NOT NULL,
	`dayOfCycle` int,
	`estradiol` decimal(7,2),
	`lh` decimal(5,2),
	`progesterone` decimal(5,2),
	`endometrialThickness` decimal(4,1),
	`follicleCountLeft` int,
	`follicleCountRight` int,
	`follicleSizesLeft` text,
	`follicleSizesRight` text,
	`medicationAdjustment` text,
	`nextVisitDate` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cycle_monitorings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `embryology_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cycleId` int NOT NULL,
	`patientId` int NOT NULL,
	`embryoNumber` int NOT NULL,
	`fertilizationMethod` enum('ivf','icsi','split'),
	`fertilizationDate` timestamp,
	`day1Score` varchar(20),
	`day2Score` varchar(20),
	`day3Score` varchar(20),
	`day4Score` varchar(20),
	`day5Score` varchar(20),
	`day6Score` varchar(20),
	`blastocystGrade` varchar(20),
	`pgtResult` enum('normal','abnormal','mosaic','no_result','pending'),
	`status` enum('developing','arrested','transferred','frozen','discarded','biopsied') NOT NULL DEFAULT 'developing',
	`freezeDate` timestamp,
	`thawDate` timestamp,
	`transferDate` timestamp,
	`storageLocation` varchar(100),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `embryology_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ivf_cycles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`doctorId` int,
	`cycleNumber` int NOT NULL DEFAULT 1,
	`cycleType` enum('ivf','icsi','iui','fet','egg_freezing','donor_egg','surrogacy') NOT NULL,
	`protocol` varchar(100),
	`startDate` timestamp,
	`stimulationStartDate` timestamp,
	`triggerDate` timestamp,
	`retrievalDate` timestamp,
	`transferDate` timestamp,
	`betaHcgDate` timestamp,
	`endDate` timestamp,
	`status` enum('planned','stimulation','trigger','retrieval','fertilization','culture','transfer','tww','pregnant','not_pregnant','cancelled','completed') NOT NULL DEFAULT 'planned',
	`eggsRetrieved` int,
	`eggsMature` int,
	`eggsFertilized` int,
	`embryosFormed` int,
	`embryosTransferred` int,
	`embryosFrozen` int,
	`outcome` enum('positive','negative','chemical','ectopic','miscarriage','ongoing','pending'),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ivf_cycles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `knowledge_content` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(300) NOT NULL,
	`slug` varchar(300) NOT NULL,
	`contentType` enum('article','video','infographic','faq','guide') NOT NULL DEFAULT 'article',
	`category` varchar(100),
	`summary` text,
	`content` text,
	`videoUrl` text,
	`thumbnailUrl` text,
	`authorId` int,
	`isPublished` boolean DEFAULT false,
	`isFeatured` boolean DEFAULT false,
	`viewCount` int DEFAULT 0,
	`tags` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `knowledge_content_id` PRIMARY KEY(`id`),
	CONSTRAINT `knowledge_content_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `lab_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`orderedBy` int,
	`testName` varchar(200) NOT NULL,
	`testCategory` enum('hormonal','blood','genetic','semen','imaging','other') NOT NULL DEFAULT 'other',
	`testDate` timestamp NOT NULL,
	`resultValue` varchar(100),
	`unit` varchar(50),
	`referenceRange` varchar(100),
	`status` enum('ordered','sample_collected','processing','completed','reviewed') NOT NULL DEFAULT 'ordered',
	`isAbnormal` boolean DEFAULT false,
	`notes` text,
	`attachmentUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lab_results_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `medications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`prescribedBy` int,
	`cycleId` int,
	`name` varchar(200) NOT NULL,
	`genericName` varchar(200),
	`dosage` varchar(100) NOT NULL,
	`frequency` varchar(100),
	`route` enum('oral','injection_sc','injection_im','vaginal','topical','nasal') DEFAULT 'oral',
	`startDate` timestamp NOT NULL,
	`endDate` timestamp,
	`status` enum('active','completed','discontinued','on_hold') NOT NULL DEFAULT 'active',
	`purpose` text,
	`sideEffects` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `medications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `patients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` varchar(20) NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320),
	`phone` varchar(20),
	`dateOfBirth` timestamp,
	`gender` enum('female','male','other') NOT NULL DEFAULT 'female',
	`bloodGroup` varchar(5),
	`address` text,
	`city` varchar(100),
	`state` varchar(100),
	`country` varchar(100),
	`emergencyContact` varchar(20),
	`emergencyContactName` varchar(100),
	`maritalStatus` enum('single','married','divorced','widowed') DEFAULT 'married',
	`partnerName` varchar(100),
	`partnerAge` int,
	`yearsOfInfertility` int,
	`previousTreatments` text,
	`medicalHistory` text,
	`allergies` text,
	`status` enum('active','inactive','completed','transferred') NOT NULL DEFAULT 'active',
	`assignedDoctorId` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `patients_id` PRIMARY KEY(`id`),
	CONSTRAINT `patients_patientId_unique` UNIQUE(`patientId`)
);
--> statement-breakpoint
CREATE TABLE `qna_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`specialistId` int,
	`question` text NOT NULL,
	`answer` text,
	`attachmentUrl` text,
	`category` varchar(100),
	`status` enum('pending','assigned','answered','closed') NOT NULL DEFAULT 'pending',
	`amount` decimal(10,2),
	`paymentStatus` enum('pending','paid','refunded') DEFAULT 'pending',
	`answeredAt` timestamp,
	`rating` int,
	`feedback` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `qna_sessions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin','doctor','nurse','embryologist','receptionist') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
